#
# tuned profile: legion-powersave
# Optimizado para Lenovo Legion 5 Pro Gen 8 (R9 7945HX + RTX 4070)
# Máxima autonomía en batería
#
[main]
summary=Legion - máxima autonomía en batería
include=powersave

[cpu]
governor=schedutil
energy_performance_preference=power
boost=0
max_perf_pct=75

[acpi]
platform_profile=low-power

[audio]
timeout=5

[video]
panel_power_savings=3

[disk]
devices=nvme*
apm=128
spindown=1

[sysctl]
vm.laptop_mode=5
vm.dirty_writeback_centisecs=1500
vm.dirty_expire_centisecs=3000
kernel.nmi_watchdog=0
vm.swappiness=10

[script]
script=${i:PROFILE_DIR}/script.sh
