#
# tuned profile: legion-powersave
# Optimizado para Lenovo Legion 5 Pro Gen 8 (R9 7945HX + RTX 4070)
# Máxima autonomía en batería (Fusión con cachyos)
#
[main]
summary=Legion - máxima autonomía en batería fusionada con CachyOS
include=cachyos-powersave

[cpu]
# Sobreescribimos el gobernador para el Ryzen 9 7945HX
governor=schedutil
energy_performance_preference=power
boost=0
max_perf_pct=75

[sysctl]
# Tus reglas maestras de disco y ram
vm.laptop_mode=5
vm.dirty_writeback_centisecs=1500
vm.dirty_expire_centisecs=3000
kernel.nmi_watchdog=0
vm.swappiness=10

[vm]
# Anulamos la paginación agresiva y vaciados prematuros de CachyOS
transparent_hugepages=madvise
dirty_bytes=0
dirty_background_bytes=0

[acpi]
platform_profile=low-power

[video]
panel_power_savings=3

[script]
script=${i:PROFILE_DIR}/script.sh
