[[main]
default=balanced
battery_detection=true
sysfs_acpi_monitor=true

[profiles]
power-saver=legion-powersave
balanced=legion-balanced
performance=legion-performance

[battery]
balanced=legion-balanced-battery
