#
# tuned profile: legion-balanced
# Optimizado para Lenovo Legion 5 Pro Gen 8 (R9 7945HX + RTX 4070)
# Balance rendimiento/consumo
#
[main]
summary=Legion - balance rendimiento y consumo
include=balanced

[cpu]
governor=schedutil
energy_performance_preference=balance_performance
boost=1

[acpi]
platform_profile=balanced

[audio]
timeout=10

[video]
panel_power_savings=1

[disk]
devices=nvme*
apm=254

[sysctl]
kernel.nmi_watchdog=0
vm.swappiness=10
vm.dirty_writeback_centisecs=500

[script]
script=${i:PROFILE_DIR}/script.sh
